In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv('https://raw.githubusercontent.com/justmarkham/DAT8/master/data/u.user', sep='\|', index_col='user_id')

<ipython-input-2-57ba2c9d23fa>:1: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df = pd.read_csv('https://raw.githubusercontent.com/justmarkham/DAT8/master/data/u.user', sep='\|', index_col='user_id')

- index_col='user_id'

In [3]:
df.head(5)

         age gender  occupation zip_code
user_id
1         24      M  technician    85711
2         53      F       other    94043
3         23      M      writer    32067
4         24      M  technician    43537
5         33      F       other    15213

In [4]:
df.tail(5)

         age gender     occupation zip_code
user_id
939       26      F        student    33319
940       32      M  administrator    02215
941       20      M        student    97229
942       48      F      librarian    78209
943       22      M        student    77841

## What is the number of observations in the dataset?

In [5]:
df.shape[0]

943

## What is the number of columns in the dataset?

In [6]:
df.shape[1]

4

## Print the name of all the columns.

In [8]:
df.columns

Index(['age', 'gender', 'occupation', 'zip_code'], dtype='object')

## How is the dataset indexed?

In [9]:
df.index

Index([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,
       ...
       934, 935, 936, 937, 938, 939, 940, 941, 942, 943],
      dtype='int64', name='user_id', length=943)

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 943 entries, 1 to 943
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   age         943 non-null    int64
 1   gender      943 non-null    object
 2   occupation  943 non-null    object
 3   zip_code    943 non-null    object
dtypes: int64(1), object(3)
memory usage: 36.8+ KB

## What is the data type of each column?

In [13]:
df.dtypes

age            int64
gender        object
occupation    object
zip_code      object
dtype: object

In [16]:
df['gender'].dtype

dtype('O')

## Print only the occupation column

In [20]:
df['occupation']

user_id
1         technician
2              other
3             writer
4         technician
5              other
           ...
939          student
940    administrator
941          student
942        librarian
943          student
Name: occupation, Length: 943, dtype: object

## How many different occupations are in this dataset?

In [26]:
df['occupation'].unique()

array(['technician', 'other', 'writer', 'executive', 'administrator',
       'student', 'lawyer', 'educator', 'scientist', 'entertainment',
       'programmer', 'librarian', 'homemaker', 'artist', 'engineer',
       'marketing', 'none', 'healthcare', 'retired', 'salesman', 'doctor'],
      dtype=object)

In [27]:
df['occupation'].nunique()

21

## What is the most frequent occupation?

In [30]:
most = df['occupation'].value_counts()
most.head(1)

occupation
student    196
Name: count, dtype: int64

In [31]:
most.head(1).index[0]

'student'

## Summarize the DataFrame.

In [32]:
df.describe()

              age
count  943.000000
mean    34.051962
std     12.192740
min      7.000000
25%     25.000000
50%     31.000000
75%     43.000000
max     73.000000

- describe(): 기본적으로 숫자형 열에 대한 통계 정보를 요약해서 보여주는 함수

## Summarize all the columns

In [33]:
df.describe(include='all')

               age gender occupation zip_code
count   943.000000    943        943      943
unique         NaN      2         21      795
top            NaN      M    student    55414
freq           NaN    670        196        9
mean     34.051962    NaN        NaN      NaN
std      12.192740    NaN        NaN      NaN
min       7.000000    NaN        NaN      NaN
25%      25.000000    NaN        NaN      NaN
50%      31.000000    NaN        NaN      NaN
75%      43.000000    NaN        NaN      NaN
max      73.000000    NaN        NaN      NaN

## Summarize only the occupation column

In [34]:
df['occupation'].describe()

count         943
unique         21
top       student
freq          196
Name: occupation, dtype: object

## What is the mean age of users?

In [39]:
round(df['age'].describe()['mean'])

34

In [40]:
round(df['age'].describe()['mean'], 2)

34.05

## What is the age with least occurrence?

In [42]:
df['age'].value_counts().tail()

age
7     1
66    1
11    1
10    1
73    1
Name: count, dtype: int64