In [1]:
import pandas as pd
import numpy as np

In [2]:
raw_data = {'regiment': ['Nighthawks', 'Nighthawks', 'Nighthawks', 'Nighthawks', 'Dragoons', 'Dragoons', 'Dragoons', 'Dragoons', 'Scouts', 'Scouts', 'Scouts', 'Scouts'],
        'company': ['1st', '1st', '2nd', '2nd', '1st', '1st', '2nd', '2nd','1st', '1st', '2nd', '2nd'],
        'name': ['Miller', 'Jacobson', 'Ali', 'Milner', 'Cooze', 'Jacon', 'Ryaner', 'Sone', 'Sloan', 'Piger', 'Riani', 'Ali'],
        'preTestScore': [4, 24, 31, 2, 3, 4, 24, 31, 2, 3, 2, 3],
        'postTestScore': [25, 94, 57, 62, 70, 25, 94, 57, 62, 70, 62, 70]}

In [3]:
df = pd.DataFrame(raw_data, columns=raw_data.keys())
df.head()

     regiment company      name  preTestScore  postTestScore
0  Nighthawks     1st    Miller             4             25
1  Nighthawks     1st  Jacobson            24             94
2  Nighthawks     2nd       Ali            31             57
3  Nighthawks     2nd    Milner             2             62
4    Dragoons     1st     Cooze             3             70

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12 entries, 0 to 11
Data columns (total 5 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   regiment       12 non-null     object
 1   company        12 non-null     object
 2   name           12 non-null     object
 3   preTestScore   12 non-null     int64
 4   postTestScore  12 non-null     int64
dtypes: int64(2), object(3)
memory usage: 608.0+ bytes

## Assign it to a variable called regiment.

## What is the mean preTestScore from the regiment Nighthawks?

In [8]:
df[df['regiment'] == 'Nighthawks'].groupby('regiment').mean(numeric_only=True)

            preTestScore  postTestScore
regiment
Nighthawks         15.25           59.5

In [10]:
nighthawks = df.loc[df['regiment'] == 'Nighthawks', 'preTestScore']
nighthawks.mean()

15.25

## Present general statistics by company.

In [13]:
company_stat = df.groupby('company').describe()
company_stat

        preTestScore                                                      \
               count       mean        std  min   25%   50%    75%   max
company
1st              6.0   6.666667   8.524475  2.0  3.00   3.5   4.00  24.0
2nd              6.0  15.500000  14.652645  2.0  2.25  13.5  29.25  31.0

        postTestScore
                count       mean        std   min    25%   50%   75%   max
company
1st               6.0  57.666667  27.485754  25.0  34.25  66.0  70.0  94.0
2nd               6.0  67.000000  14.057027  57.0  58.25  62.0  68.0  94.0

## What is the mean of each company's preTestScore?

In [15]:
each_com = df.groupby('company')['preTestScore'].mean()
each_com

company
1st     6.666667
2nd    15.500000
Name: preTestScore, dtype: float64

## Present the mean preTestScores grouped by regiment and company.

In [17]:
df.groupby(['regiment', 'company'])['preTestScore'].mean()

regiment    company
Dragoons    1st         3.5
            2nd        27.5
Nighthawks  1st        14.0
            2nd        16.5
Scouts      1st         2.5
            2nd         2.5
Name: preTestScore, dtype: float64

## Group the entire dataframe by regiment and company.

In [24]:
entire = df.groupby(['regiment', 'company']).mean(numeric_only=True)
entire

                    preTestScore  postTestScore
regiment   company
Dragoons   1st               3.5           47.5
           2nd              27.5           75.5
Nighthawks 1st              14.0           59.5
           2nd              16.5           59.5
Scouts     1st               2.5           66.0
           2nd               2.5           66.0

## What is the number of observations in each regiment and company.

In [29]:
df.groupby(['regiment', 'company']).size()

regiment    company
Dragoons    1st        2
            2nd        2
Nighthawks  1st        2
            2nd        2
Scouts      1st        2
            2nd        2
dtype: int64

- size(): DataFrame에서 전체 요소 개수(값의 개수)를 반환하는 메소드

## Iterate over a group and print the name and the whole data from the regiment.
> 그룹을 반복하고 연대의 이름과 전체 데이터를 출력

In [30]:
copy = df.groupby('regiment')
copy.head()

      regiment company      name  preTestScore  postTestScore
0   Nighthawks     1st    Miller             4             25
1   Nighthawks     1st  Jacobson            24             94
2   Nighthawks     2nd       Ali            31             57
3   Nighthawks     2nd    Milner             2             62
4     Dragoons     1st     Cooze             3             70
5     Dragoons     1st     Jacon             4             25
6     Dragoons     2nd    Ryaner            24             94
7     Dragoons     2nd      Sone            31             57
8       Scouts     1st     Sloan             2             62
9       Scouts     1st     Piger             3             70
10      Scouts     2nd     Riani             2             62
11      Scouts     2nd       Ali             3             70

In [31]:
# Iterate over a group
for name, group in copy:
    print(name)
    print(group)

Dragoons
   regiment company    name  preTestScore  postTestScore
4  Dragoons     1st   Cooze             3             70
5  Dragoons     1st   Jacon             4             25
6  Dragoons     2nd  Ryaner            24             94
7  Dragoons     2nd    Sone            31             57
Nighthawks
     regiment company      name  preTestScore  postTestScore
0  Nighthawks     1st    Miller             4             25
1  Nighthawks     1st  Jacobson            24             94
2  Nighthawks     2nd       Ali            31             57
3  Nighthawks     2nd    Milner             2             62
Scouts
   regiment company   name  preTestScore  postTestScore
8    Scouts     1st  Sloan             2             62
9    Scouts     1st  Piger             3             70
10   Scouts     2nd  Riani             2             62
11   Scouts     2nd    Ali             3             70

- name: 그룹화에 사용된 regiment 열의 고유값: 각 그룹을 대표하는 이름
- group: 해당 그룹에 속하는 DataFrame 부분